kind = "web"
previewPath = "/"
title = "Absensi LWP"
version = "1.0.0"
id = "artifacts/absensi-lwp"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22664

[services.development]
run = "pnpm --filter @workspace/absensi-lwp run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/absensi-lwp", "run", "build" ]
publicDir = "artifacts/absensi-lwp/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22664"
BASE_PATH = "/"
